bucket.settings:
  type: config_object
  label: 'Bucket settings'
  mapping:
    ttl_hours:
      type: integer
      label: 'Time-to-live (hours)'
    delete_on_download:
      type: boolean
      label: 'Delete file immediately after download'
    use_blocklist:
      type: boolean
      label: 'Use blocklist (disallow list) instead of allowlist'
    allowed_extensions:
      type: string
      label: 'Allowed file extensions (space-separated, leave blank to allow all)'
    blocked_extensions:
      type: string
      label: 'Blocked file extensions (space-separated)'
    permissive_extensions:
      type: text
      label: 'Permissive allowlist used to override Drupal defaults in blocklist mode'
    max_filesize_mb:
      type: integer
      label: 'Max file size (MB)'
    list_page_limit:
      type: integer
      label: 'List page limit'
    description:
      type: text
      label: 'Description shown on list/upload pages (supports [ttl_hours], [delete_on_download])'
